<?php
/**
 * Plugin Name: Gigya - Make Your Site Social
 * Plugin URI: http://gigya.com
 * Description: Allows sites to utilize the Gigya API for authentication and social network updates.
 * Version: 5.0
 * Author: Gigya
 * Author URI: http://gigya.com
 * License: GPL2+
 */
define( 'GIGYA__MINIMUM_WP_VERSION', '3.5' );
define( 'GIGYA__MINIMUM_PHP_VERSION', '5.2' );
define( 'GIGYA__VERSION', '5.0' );
define( 'GIGYA__PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'GIGYA__SETTINGS_PREFIX', 'gigya_settings_fields' );

require_once( GIGYA__PLUGIN_DIR . 'sdk/GSSDK.php' );
require_once( GIGYA__PLUGIN_DIR . 'class/class.GigyaUser.php' );
require_once( GIGYA__PLUGIN_DIR . 'class/class.GigyaApi.php' );
require_once( GIGYA__PLUGIN_DIR . 'admin/admin.GigyaConfig.php' );
require_once( GIGYA__PLUGIN_DIR . 'admin/admin.GigyaConfigPages.php' );


/**
 * Renders a default template.
 *
 * @param $template_file
 *   The filename of the template to render.
 * @param $variables
 *   A keyed array of variables that will appear in the output.
 *
 * @return void The output generated by the template.
 */
function _gigya_render_tpl($template_file, $variables) {
	// Extract the variables to a local namespace
	extract($variables, EXTR_SKIP);

	// Start output buffering
	ob_start();

	// Include the template file
	include GIGYA__PLUGIN_DIR . '/' . $template_file;

	// End buffering and return its contents
	$output = ob_get_clean();
	echo $output;
}



/**
 * Render form elements.
 * @param $vars
 */
function _gigya_formEl($vars) {
	$render = _gigya_render_tpl('admin/tpl/formEl-' . $vars['type'] . '.tpl.php', $vars);
	return $render;
}